{% set name = "cuda-api-wrappers" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eyalroz/cuda-api-wrappers/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fa30c9fe43a62f5a3fd82a5deb477838fbf0bf455c73a2d2bb5ab6284184900b

build:
  number: 0
  skip: True  # [cuda_compiler_version == 'None']

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja

test:
  commands:
    - test -f ${PREFIX}/include/cuda/api.hpp
    - test -f ${PREFIX}/include/cuda/rtc.hpp
    - test -f ${PREFIX}/include/cuda/nvtx.hpp
    - test -f ${PREFIX}/include/cuda/runtime_api.hpp
    - test -f ${PREFIX}/lib/cmake/cuda-api-wrappers/cuda-api-wrappers-config.cmake
    - test -f ${PREFIX}/lib/cmake/cuda-api-wrappers/cuda-api-wrappers-targets.cmake

about:
  home: https://github.com/eyalroz/cuda-api-wrappers
  summary: Thin, unified, C++-flavored wrappers for the CUDA APIs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://codedocs.xyz/eyalroz/cuda-api-wrappers/
  dev_url: https://github.com/eyalroz/cuda-api-wrappers

extra:
  recipe-maintainers:
    - awvwgk
